services:
  db:
    image: postgres:14
    container_name: dq-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./.data/db:/var/lib/postgresql/data
